import Foundation

public struct CaddySettings: Codable, Sendable {
    public var executable: String
    public var config: String
    public init(executable: String, config: String) { self.executable = executable; self.config = config }
}

public struct Caddy: Sendable {
    public let paths: AppPaths
    public init(paths: AppPaths = AppPaths()) { self.paths = paths }
    public var routes: URL { paths.root.appendingPathComponent("routes.caddyfile") }
    public var settingsFile: URL { paths.root.appendingPathComponent("caddy.json") }
    public var configured: Bool { FileManager.default.fileExists(atPath: settingsFile.path) }

    public static func domain(_ url: String) throws -> String {
        guard let address = URLComponents(string: url), address.scheme == "http",
              let host = address.host, host.hasSuffix(".localhost"), host.count <= 253,
              address.port == nil, address.user == nil, address.password == nil,
              address.query == nil, address.fragment == nil,
              address.path.isEmpty || address.path == "/",
              host.split(separator: ".", omittingEmptySubsequences: false).allSatisfy({
                  $0.range(of: "^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$", options: .regularExpression) != nil
              }) else { throw LocalBarError("Use an HTTP domain such as my-app.localhost, without a port or path.") }
        return host.lowercased()
    }

    public static func render(_ services: [Service]) throws -> String {
        var domains = Set<String>()
        return try services.map { service in
            try service.validate()
            let host = try domain(service.url)
            guard domains.insert(host).inserted else { throw LocalBarError("Duplicate domain: \(host)") }
            return "http://\(host) {\n\tbind 127.0.0.1 ::1\n\treverse_proxy localhost:\(service.port)\n}\n"
        }.joined(separator: "\n") + "\n# Generated by Local Bar. Edit servers in the app.\n"
    }

    public static func adoptingSimpleRoutes(in text: String, services: [Service]) throws -> String {
        var result = text
        for service in services {
            let host = NSRegularExpression.escapedPattern(for: try domain(service.url))
            let pattern = "(?m)^http://" + host + "[ \t]*\\{\\s*bind[ \t]+127\\.0\\.0\\.1[ \t]+::1\\s*reverse_proxy[ \t]+(?:localhost|127\\.0\\.0\\.1):" + String(service.port) + "[ \t]*\\s*\\}[ \t]*$"
            let regex = try NSRegularExpression(pattern: pattern)
            result = regex.stringByReplacingMatches(in: result, range: NSRange(result.startIndex..., in: result), withTemplate: "")
        }
        return result
    }

    // Keep the previous routes if validation or reload fails.
    public func apply(_ services: [Service]) async throws {
        let data = Data(try Self.render(services).utf8)
        let previous = try? Data(contentsOf: routes)
        try data.write(to: routes, options: .atomic)
        guard configured else { return }
        do {
            let settings = try JSONDecoder().decode(CaddySettings.self, from: Data(contentsOf: settingsFile))
            let root = try String(contentsOfFile: settings.config, encoding: .utf8)
            guard root.contains("import \"\(routes.path)\"") else {
                throw LocalBarError("Caddy's configuration no longer imports Local Bar routes. Run scripts/setup-caddy.sh again.")
            }
            for action in ["validate", "reload"] {
                let result = try await Commands.run(settings.executable, [action, "--config", settings.config, "--adapter", "caddyfile"])
                guard result.status == 0 else { throw LocalBarError("Caddy \(action) failed. Your changes were not applied.\n\n\(result.output)") }
            }
        } catch {
            if let previous { try previous.write(to: routes, options: .atomic) }
            else { try? FileManager.default.removeItem(at: routes) }
            throw error
        }
    }
}
